### ISSUE TITLE
Cannot compile on macOS Sierra Qt 5.7

### ISSUE THREAD

**Issue by kildevaeld** [frankosterfeld/qtkeychain#92] opened 2016-10-26 18:14 UTC
The moc compiler fails, because of a forward declaration to `QDBusPendingCallWatcher` in `keychain_p.h`.

**Comment by frankosterfeld** [comment] 2017-04-19 13:14
Cannot reproduce (macos 10.12.4, XCode 8.3.2, Qt 5.7.1) , the types are declared but never used, so it shouldn't be a problem?

**Comment by frankosterfeld** [comment] 2017-04-19 13:15
Closing, please reopen if you still see this with latest master or 0.8 branches.

**Closed by frankosterfeld** 2017-04-19 13:15 UTC
