### ISSUE TITLE
Invalid qt_Qt5Keychain.pri

### ISSUE THREAD

**Issue by Ri0n** [frankosterfeld/qtkeychain#141] opened 2019-03-28 10:24 UTC
Hi

I'm using openSUSE and noticed I can't use qtkeychain in my qmake based project.
When I add Qt5Keychain to QT it compiles but fails on linking stage because keychain library is not added to linking command line.

After some digging around I figured out the problem is in missing `QT.Qt5Keychain.module = qt5keychain` line in qt_Qt5Keychain.pri file.

I reported this to SUSE https://bugzilla.suse.com/show_bug.cgi?id=1130608 and they said it's upstream bug. So I'm writing here now.

I can provide more details later if necessary.

**Comment by Vogtinator** [comment] 2019-03-28 10:48
The issue is that the bundled version of ECMGeneratePriFile is outdated and does not work with Qt 5.12.1+. It needs at least this change: https://cgit.kde.org/extra-cmake-modules.git/commit/modules/ECMGeneratePriFile.cmake?id=79bf23008f666b358b03a70068bf6ae27a9b1967

**Comment by frankosterfeld** [comment] 2021-01-18 08:13
This seems fixed now? Please reopen if not.

**Closed by frankosterfeld** 2021-01-18 08:13 UTC

**Comment by Vogtinator** [comment] 2021-01-18 08:23
Yep, confirmed.
